# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WangYe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	
  # Pods for WangYe
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'YYKit'
    pod 'BlocksKit'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'CHTCollectionViewWaterfallLayout'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'iCarousel'
    pod 'WMPageController'
    pod 'MWPhotoBrowser'
    pod 'MLTransition'
    pod 'HcdCachePlayer'
end
